# Generated by Django 3.1.7 on 2021-04-30 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='タグ名')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('description', models.CharField(max_length=2000, verbose_name='動画説明文')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('edited', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='tube/image', verbose_name='画像')),
                ('movie', models.FileField(blank=True, upload_to='tube/movie', verbose_name='動画')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tube.category', verbose_name='カテゴリ')),
                ('tag', models.ManyToManyField(blank=True, to='tube.Tag', verbose_name='タグ')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
