# Generated by Django 3.1.7 on 2021-04-30 05:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20210430_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='コメント文')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='コメント先の動画')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
