# Generated by Django 3.1.7 on 2021-05-01 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
    ]
