# Generated by Django 3.1.7 on 2021-05-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_videocomment_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
